export const FETCH_STATE_WATCHER = "FETCH_STATE_WATCHER";
export const FETCH_CITY_WATCHER = "FETCH_CITY_WATCHER";

export const SET_STATES = "SET_STATES";
export const SET_CITY = "SET_CITY";

export const SET_STATES_ERROR = "SET_STATES_ERROR";
export const SET_CITY_ERROR = "SET_CITY_ERROR";

export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SET_EMPLOYEE = "SET_EMPLOYEE";

export const SET_EMPLOYEE_FORM = "SET_EMPLOYEE_FORM";
export const SET_EMPLOYEES_ERROR = "SET_EMPLOYEES_ERROR";

export const FETCH_EMPLOYEES_WATCHER = "FETCH_EMPLOYEES_WATCHER";
export const FETCH_EMPLOYEE_BY_ID_WATCHER = "FETCH_EMPLOYEE_BY_ID_WATCHER";
export const CREATE_EMPLOYEES_WATCHER = "CREATE_EMPLOYEES_WATCHER";
export const DELETE_EMPLOYEES_WATCHER = "DELETE_EMPLOYEES_WATCHER";
export const UPDATE_EMPLOYEES_WATCHER = "UPDATE_EMPLOYEES_WATCHER";

export const FETCH_TICKETS_WATCHER = "FETCH_TICKETS_WATCHER";
export const FETCH_TICKETS_BY_ID_WATCHER = "FETCH_TICKETS_BY_ID_WATCHER";
export const CREATE_TICKETS_WATCHER = "CREATE_TICKETS_WATCHER";
export const CREATE_BULK_TICKETS_WATCHER = "CREATE_BULK_TICKETS_WATCHER";
export const DELETE_TICKETS_WATCHER = "DELETE_TICKETS_WATCHER";
export const UPDATE_TICKETS_WATCHER = "UPDATE_TICKETS_WATCHER";
export const UPLOAD_TICKETS_WATCHER = "UPLOAD_TICKETS_WATCHER";

export const CREATE_BUSINESSCLIENTS_WATCHER = "CREATE_BUSINESSCLIENTS_WATCHER";

export const FETCH_BUSINESSCLIENT_WATCHER = "FETCH_BUSINESSCLIENT_WATCHER";
export const SET_BUSINESSCLIENT_LIST = "SET_BUSINESSCLIENT_LIST";
export const SET_BUSINESSCLIENT_LIST_ERROR = "SET_BUSINESSCLIENT_LIST_ERROR";
export const FETCH_BUSINESSCLIENT_BY_ID_WATCHER = "FETCH_BUSINESSCLIENT_BY_ID_WATCHER";

export const SET_BUSINESSCLIENT = "SET_BUSINESSCLIENT";
export const SET_BUSINESSCLIENT_ERROR = "SET_BUSINESSCLIENT_ERROR";


export const UPDATE_BUSINESSCLIENTS_WATCHER = "UPDATE_BUSINESSCLIENTS_WATCHER"
export const SET_TICKETS = "SET_TICKETS";
export const RESET_TICKETS_PAGINATION = "RESET_TICKETS_PAGINATION";
export const SET_TICKET = "SET_TICKET";
export const SET_TICKETS_ERROR = "SET_TICKETS_ERROR";

export const FETCH_BRAND_WATCHER = "FETCH_BRAND_WATCHER";
export const SET_BRAND = "SET_BRAND";
export const SET_ClEAR = "SET_ClEAR"
export const SET_BRAND_ERROR = "SET_BRAND_ERROR";
export const FETCH_All_CITY_WATCHER = "FETCH_All_CITY_WATCHER";

export const FETCH_PRODUCT_BY_BRAND_ID_WATCHER = "FETCH_PRODUCT_BY_BRAND_ID_WATCHER";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";

export const SET_PRODUCT_SUBCATEGORY_ERROR = "SET_PRODUCT_SUBCATEGORY_ERROR";
export const SET_PRODUCT_SUBCATEGORY = "SET_PRODUCT_SUBCATEGORY";
export const FETCH_PRODUCT_SUBCATEGORY_BY_BRAND_ID_AND_PRODUCTID_WATCHER = "FETCH_PRODUCT_SUBCATEGORY_BY_BRAND_ID_AND_PRODUCTID_WATCHER";
export const FETCH_ALL_PRODUCTSUB_CATEGORY_WATCHER = "FETCH_ALL_PRODUCTSUB_CATEGORY_WATCHER";
export const FETCH_MODEL_BY_PRODUCT_ID_WATCHER = "FETCH_MODEL_BY_PRODUCT_ID_WATCHER";
export const SET_MODEL = "SET_MODEL";
export const SET_MODEL_ERROR = "SET_MODEL_ERROR";
export const FETCH_ALL_PRODUCT_WATCHER = "FETCH_ALL_PRODUCT_WATCHER";
export const FETCH_ALL_MODEL_WATCHER = "FETCH_ALL_MODEL_WATCHER";
export const IMAGE_UPLOAD_WATCHER = "IMAGE_UPLOAD_WATCHER";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const PAGE_LOADER_START = "PAGE_LOADER_START";
export const PAGE_LOADER_FINISH = "PAGE_LOADER_FINISH";
export const SHOW_TOAST_MESSAGE = "SHOW_TOAST_MESSAGE";
export const HIDE_TOAST_MESSAGE = "HIDE_TOAST_MESSAGE";


